name: SSH test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Connect
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i ~/.ssh/id_ed25519 \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "echo CONNECTION_OK"
